### ISSUE TITLE
No API response: request to `supplemental/query` with `order` as one of the `colsWanted` the API does not return a response

### ISSUE THREAD

**Issue by rahulAgrBej** [Seafood-Globalization-Lab/ARTIS-API#2]
Request to `supplemental/query` with `order` as one of the `colsWanted` the API does not return a response.

> "If I make a request to `supplemental/query` with `order` as one of the `colsWanted` the API does not return a response. I've included the exact request below for you to reproduce. Obviously this is a small issue that needs to be addressed, but the bigger concern is that the API returned nothing at all rather than an error code. It's definitely important that any request that does not get processed correctly return the appropriate error code so we can catch these issues in development."

Sample request:

`{
"table": "sciname",
"colsWanted": ["order"],
"searchCriteria": {
"sciname": ["salmo salar"]
}
}
`

**Comment by andymangold** [comment]
Some additional context on this issue: I get the same non-response when specifying an `order` as a `searchCriteria`, i.e.:

```
{
    "table": "sciname",
    "colsWanted": ["sciname"],
    "searchCriteria": {
        "order": ["salmoniformes"]
    }
}
```

This is the same behavior I am experiencing when filtering for a class, documented in #4

**Comment by rahulAgrBej** [comment]
Resolved.
